/* ******************************************************************************
 * 	
 * 	Name	: ConsoleColorChooserDialog.java
 * 	Type	: com.gs.jprompt.app.form.ConsoleColorChooserDialog
 * 
 * 	Created	: Feb 22, 2012
 * 	
 * 	Author	: Sabuj Das [ mailto::sabuj.das@gmail.com ]
 * 
 * -----------------------------------------------------------------------------*
 * 																				*
 * Copyright © Sabuj Das 2010 All Rights Reserved. 								*
 * <br/>No part of this document may be reproduced without written 				*
 * consent from the author.														*
 * 																				*
 ****************************************************************************** */

package com.gs.jprompt.app.form;

import java.awt.Color;

import com.gs.utils.swing.window.WindowUtil;

/**
 * @author sabuj.das
 * @MailTo sabuj.das@gmail.com
 * 
 */
public class ConsoleColorChooserDialog extends javax.swing.JDialog {

	public static final int OK_OPTION = 1110;
    public static final int CANCEL_OPTION = 1111;
    
    private final Color oldFGColor;
    private final Color oldBGColor;
    
    private Color selectedFGColor;
    private Color selectedBGColor;
    
    private int selectedOption = CANCEL_OPTION;
    
    /** Creates new form ColorChooserDialog */
    public ConsoleColorChooserDialog(java.awt.Frame parent, boolean modal,
            Color oldFGColor, Color oldBGColor) {
        super(parent, modal);
        this.oldFGColor = oldFGColor;
        this.oldBGColor = oldBGColor;
        initComponents();
        fgColorChooser.setColor(oldFGColor);
        bgColorChooser.setColor(oldBGColor);
        WindowUtil.bringCenterTo(this, parent);
    }

    public int getSelectedOption() {
        return selectedOption;
    }
    public int showFontChooserDialog(){
        this.setVisible(true);
        return selectedOption;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        fgColorChooser = new javax.swing.JColorChooser();
        bgColorChooser = new javax.swing.JColorChooser();
        cancelButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(formListener);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("Foreground Color", fgColorChooser);
        jTabbedPane1.addTab("Background Color", bgColorChooser);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jPanel1, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(formListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(cancelButton, gridBagConstraints);

        selectButton.setText("Select");
        selectButton.addActionListener(formListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(selectButton, gridBagConstraints);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.WindowListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == cancelButton) {
            	ConsoleColorChooserDialog.this.cancelButtonActionPerformed(evt);
            }
            else if (evt.getSource() == selectButton) {
            	ConsoleColorChooserDialog.this.selectButtonActionPerformed(evt);
            }
        }

        public void windowActivated(java.awt.event.WindowEvent evt) {
        }

        public void windowClosed(java.awt.event.WindowEvent evt) {
            if (evt.getSource() == ConsoleColorChooserDialog.this) {
            	ConsoleColorChooserDialog.this.formWindowClosed(evt);
            }
        }

        public void windowClosing(java.awt.event.WindowEvent evt) {
        }

        public void windowDeactivated(java.awt.event.WindowEvent evt) {
        }

        public void windowDeiconified(java.awt.event.WindowEvent evt) {
        }

        public void windowIconified(java.awt.event.WindowEvent evt) {
        }

        public void windowOpened(java.awt.event.WindowEvent evt) {
        }
    }// </editor-fold>

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        selectedFGColor = oldFGColor;
        selectedBGColor = oldBGColor;
        selectedOption = CANCEL_OPTION;
        dispose();
    }

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {
        selectedFGColor = fgColorChooser.getColor();
        selectedBGColor = bgColorChooser.getColor();
        selectedOption = OK_OPTION;
        dispose();
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        selectedFGColor = oldFGColor;
        selectedBGColor = oldBGColor;
        selectedOption = CANCEL_OPTION;
        selectedOption = CANCEL_OPTION;
        
    }

    public Color getSelectedBGColor() {
        return selectedBGColor;
    }

    public Color getSelectedFGColor() {
        return selectedFGColor;
    }

    
   
    // Variables declaration - do not modify
    private javax.swing.JColorChooser bgColorChooser;
    private javax.swing.JButton cancelButton;
    private javax.swing.JColorChooser fgColorChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton selectButton;
    // End of variables declaration
	
}
