/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sf.tools.gsplit.ui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import net.sf.tools.gsplit.ResourceBundleManager;
import net.sf.tools.gsplit.SplitterConstants;
import net.sf.tools.gsplit.SplitterContext;
import net.sf.tools.gsplit.ui.core.FlatJoinPanel;
import net.sf.tools.gsplit.ui.core.FlatSplitPanel;
import net.sf.tools.gsplit.ui.core.PdfJoinPanel;
import net.sf.tools.gsplit.ui.core.PdfSplitPanel;
import net.sf.tools.gsplit.ui.core.SecureJoinPanel;
import net.sf.tools.gsplit.ui.core.SecureSplitPanel;
import net.sf.tools.gsplit.ui.core.SettingsPanel;
import net.sf.tools.gsplit.ui.core.TextJoinPanel;
import net.sf.tools.gsplit.ui.core.TextSplitPanel;
import net.sf.tools.gsplit.ui.core.XmlJoinPanel;
import net.sf.tools.gsplit.ui.core.XmlSplitPanel;
import net.sf.tools.gsplit.util.WindowUtil;

/**
 *
 * @author SG1736
 */
public class GsplitBaseFrame extends javax.swing.JFrame {

    private static final WindowManager WINDOW_MANAGER = WindowManager.getManager();
    private static final SplitterContext context = SplitterContext.getContext();
    private ResourceBundle bundle = ResourceBundleManager.getBundleManager().getResourceBundle();

    /**
     * Creates new form GsplitBaseFrame
     */
    public GsplitBaseFrame() {
        setTitle(bundle.getString("app.title")
                + " " + bundle.getString("app.version"));
        setSize(800, 640);
        setMinimumSize(getSize());
        setIconImage((new ImageIcon(getClass()
                .getResource("/images/file-splitter-icon_24x24.png"))).getImage());
        WindowUtil.bringToCenter(this);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        initComponents();
        WINDOW_MANAGER.baseDesktopPane = this.baseDesktopPane;
        WINDOW_MANAGER.windowManagerLabel = this.windowManagerLabel;
        WINDOW_MANAGER.windowManagerPopupMenu = this.windowManagerPopupMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        baseDesktopPopupMenu = new javax.swing.JPopupMenu();
        minimizeAllMenuItem = new javax.swing.JMenuItem();
        maximizeAllMenuItem = new javax.swing.JMenuItem();
        windowManagerPopupMenu = new javax.swing.JPopupMenu();
        showAllMenuItem = new javax.swing.JMenuItem();
        openMdatMenuItem = new javax.swing.JMenuItem();
        openLogFileMenuItem = new javax.swing.JMenuItem();
        flatSplitButton = new javax.swing.JButton();
        flatJoinButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        xmlMenu = new javax.swing.JMenu();
        xmlSplitMenuItem = new javax.swing.JMenuItem();
        xmlJoinMenuItem = new javax.swing.JMenuItem();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jButton6 = new javax.swing.JButton();
        baseToolBar = new javax.swing.JToolBar();
        secureSplitButton = new javax.swing.JButton();
        secureJoinButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        editSettingsButton = new javax.swing.JButton();
        baseStatusBar = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        windowManagerLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        baseDesktopPane = new javax.swing.JDesktopPane();
        desktopImageLabel = new javax.swing.JLabel();
        baseMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        secureSplitMenuItem = new javax.swing.JMenuItem();
        secureJoinMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        flatSplitMenuItem = new javax.swing.JMenuItem();
        flatJoinMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        textMenu = new javax.swing.JMenu();
        textSplitMenuItem = new javax.swing.JMenuItem();
        textJoinMenuItem = new javax.swing.JMenuItem();
        pdfMenu = new javax.swing.JMenu();
        pdfSplitMenuItem = new javax.swing.JMenuItem();
        pdfJoinMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        minimize2trayMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        settingsMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        showToolbarChkbxMenuItem = new javax.swing.JCheckBoxMenuItem();
        showStatusbarChkbxMenuItem = new javax.swing.JCheckBoxMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        showLogMenuItem = new javax.swing.JMenuItem();
        exploreLogFolderMenuItem = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        windowsMenu = new javax.swing.JMenu();
        windowsTilesMenuItem = new javax.swing.JMenuItem();
        windowsCascadeMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        minimizeAllMenuItem.setText("Minimize All");
        minimizeAllMenuItem.addActionListener(formListener);
        baseDesktopPopupMenu.add(minimizeAllMenuItem);

        maximizeAllMenuItem.setText("Maximize All");
        maximizeAllMenuItem.addActionListener(formListener);
        baseDesktopPopupMenu.add(maximizeAllMenuItem);

        showAllMenuItem.setText("Show All");
        showAllMenuItem.addActionListener(formListener);
        windowManagerPopupMenu.add(showAllMenuItem);

        openMdatMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMdatMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-splitter_16x16.png"))); // NOI18N
        openMdatMenuItem.setText("Open Metadata file");
        openMdatMenuItem.addActionListener(formListener);

        openLogFileMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder_open_document_text.png"))); // NOI18N
        openLogFileMenuItem.setText("Open Log File");
        openLogFileMenuItem.addActionListener(formListener);

        flatSplitButton.setText("jButton3");
        flatSplitButton.setFocusable(false);
        flatSplitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        flatSplitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        flatJoinButton.setText("jButton4");
        flatJoinButton.setFocusable(false);
        flatJoinButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        flatJoinButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        xmlMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xml.png"))); // NOI18N
        xmlMenu.setText("XML");

        xmlSplitMenuItem.setText(bundle.getString("GsplitBaseFrame.xmlSplitMenuItem.text")); // NOI18N
        xmlSplitMenuItem.addActionListener(formListener);
        xmlMenu.add(xmlSplitMenuItem);

        xmlJoinMenuItem.setText(bundle.getString("GsplitBaseFrame.xmlJoinMenuItem.text")); // NOI18N
        xmlJoinMenuItem.addActionListener(formListener);
        xmlMenu.add(xmlJoinMenuItem);

        jLabel4.setText("Current Process ");

        jProgressBar2.setEnabled(false);
        jProgressBar2.setMaximumSize(new java.awt.Dimension(160, 19));
        jProgressBar2.setMinimumSize(new java.awt.Dimension(160, 19));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop.png"))); // NOI18N
        jButton6.setToolTipText("Stop");
        jButton6.setEnabled(false);
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(formListener);

        baseToolBar.setFloatable(false);
        baseToolBar.setRollover(true);

        secureSplitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-split.png"))); // NOI18N
        secureSplitButton.setFocusable(false);
        secureSplitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        secureSplitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        secureSplitButton.addActionListener(formListener);
        baseToolBar.add(secureSplitButton);

        secureJoinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-join.png"))); // NOI18N
        secureJoinButton.setFocusable(false);
        secureJoinButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        secureJoinButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        secureJoinButton.addActionListener(formListener);
        baseToolBar.add(secureJoinButton);
        baseToolBar.add(jSeparator6);

        editSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        editSettingsButton.setFocusable(false);
        editSettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editSettingsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editSettingsButton.addActionListener(formListener);
        baseToolBar.add(editSettingsButton);

        getContentPane().add(baseToolBar, java.awt.BorderLayout.PAGE_START);

        baseStatusBar.setFloatable(false);
        baseStatusBar.setRollover(true);
        baseStatusBar.setMaximumSize(new java.awt.Dimension(36, 25));
        baseStatusBar.setMinimumSize(new java.awt.Dimension(47, 23));
        baseStatusBar.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel1.setText(" ");
        baseStatusBar.add(jLabel1);

        windowManagerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/window-manager_24x24.png"))); // NOI18N
        windowManagerLabel.setText("Window Manager");
        windowManagerLabel.setEnabled(false);
        windowManagerLabel.addMouseListener(formListener);
        baseStatusBar.add(windowManagerLabel);
        baseStatusBar.add(jSeparator5);

        statusPanel.setLayout(new java.awt.GridBagLayout());

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        statusPanel.add(statusLabel, gridBagConstraints);

        baseStatusBar.add(statusPanel);
        baseStatusBar.add(jSeparator8);

        getContentPane().add(baseStatusBar, java.awt.BorderLayout.PAGE_END);

        baseDesktopPane.setComponentPopupMenu(baseDesktopPopupMenu);
        baseDesktopPane.setDoubleBuffered(true);
        baseDesktopPane.setMinimumSize(new java.awt.Dimension(500, 300));
        baseDesktopPane.setPreferredSize(new java.awt.Dimension(640, 350));
        baseDesktopPane.addComponentListener(formListener);

        desktopImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-splitter_256x256.png"))); // NOI18N
        desktopImageLabel.setBounds(364, 114, 260, 240);
        baseDesktopPane.add(desktopImageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(baseDesktopPane, java.awt.BorderLayout.CENTER);

        fileMenu.setText(bundle.getString("GsplitBaseFrame.fileMenu.text")); // NOI18N

        secureSplitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        secureSplitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-split.png"))); // NOI18N
        secureSplitMenuItem.setText(bundle.getString("GsplitBaseFrame.secureSplitMenuItem.text")); // NOI18N
        secureSplitMenuItem.addActionListener(formListener);
        fileMenu.add(secureSplitMenuItem);

        secureJoinMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        secureJoinMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-join.png"))); // NOI18N
        secureJoinMenuItem.setText(bundle.getString("GsplitBaseFrame.secureJoinMenuItem.text")); // NOI18N
        secureJoinMenuItem.addActionListener(formListener);
        fileMenu.add(secureJoinMenuItem);
        fileMenu.add(jSeparator1);

        flatSplitMenuItem.setText(bundle.getString("GsplitBaseFrame.flatSplitMenuItem.text")); // NOI18N
        flatSplitMenuItem.addActionListener(formListener);
        fileMenu.add(flatSplitMenuItem);

        flatJoinMenuItem.setText(bundle.getString("GsplitBaseFrame.flatJoinMenuItem.text")); // NOI18N
        flatJoinMenuItem.addActionListener(formListener);
        fileMenu.add(flatJoinMenuItem);
        fileMenu.add(jSeparator2);

        textMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/text-file.png"))); // NOI18N
        textMenu.setText("Text");

        textSplitMenuItem.setText(bundle.getString("GsplitBaseFrame.textSplitMenuItem.text")); // NOI18N
        textSplitMenuItem.addActionListener(formListener);
        textMenu.add(textSplitMenuItem);

        textJoinMenuItem.setText(bundle.getString("GsplitBaseFrame.textJoinMenuItem.text")); // NOI18N
        textJoinMenuItem.addActionListener(formListener);
        textMenu.add(textJoinMenuItem);

        fileMenu.add(textMenu);

        pdfMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        pdfMenu.setText("PDF");

        pdfSplitMenuItem.setText(bundle.getString("GsplitBaseFrame.pdfSplitMenuItem.text")); // NOI18N
        pdfSplitMenuItem.addActionListener(formListener);
        pdfMenu.add(pdfSplitMenuItem);

        pdfJoinMenuItem.setText(bundle.getString("GsplitBaseFrame.pdfJoinMenuItem.text")); // NOI18N
        pdfJoinMenuItem.addActionListener(formListener);
        pdfMenu.add(pdfJoinMenuItem);

        fileMenu.add(pdfMenu);
        fileMenu.add(jSeparator4);

        minimize2trayMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        minimize2trayMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        minimize2trayMenuItem.setText(bundle.getString("GsplitBaseFrame.minimize2trayMenuItem.text")); // NOI18N
        minimize2trayMenuItem.addActionListener(formListener);
        fileMenu.add(minimize2trayMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitMenuItem.setText(bundle.getString("GsplitBaseFrame.exitMenuItem.text")); // NOI18N
        exitMenuItem.addActionListener(formListener);
        fileMenu.add(exitMenuItem);

        baseMenuBar.add(fileMenu);

        editMenu.setText(bundle.getString("GsplitBaseFrame.editMenu.text")); // NOI18N

        settingsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        settingsMenuItem.setText(bundle.getString("GsplitBaseFrame.settingsMenuItem.text")); // NOI18N
        settingsMenuItem.addActionListener(formListener);
        editMenu.add(settingsMenuItem);

        baseMenuBar.add(editMenu);

        viewMenu.setText(bundle.getString("GsplitBaseFrame.viewMenu.text")); // NOI18N

        showToolbarChkbxMenuItem.setSelected(true);
        showToolbarChkbxMenuItem.setText(bundle.getString("GsplitBaseFrame.showToolbarChkbxMenuItem.text")); // NOI18N
        showToolbarChkbxMenuItem.addActionListener(formListener);
        viewMenu.add(showToolbarChkbxMenuItem);

        showStatusbarChkbxMenuItem.setSelected(true);
        showStatusbarChkbxMenuItem.setText(bundle.getString("GsplitBaseFrame.showStatusbarChkbxMenuItem.text")); // NOI18N
        showStatusbarChkbxMenuItem.addActionListener(formListener);
        viewMenu.add(showStatusbarChkbxMenuItem);
        viewMenu.add(jSeparator9);

        showLogMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file_extension_log.png"))); // NOI18N
        showLogMenuItem.setText(bundle.getString("GsplitBaseFrame.showLogMenuItem.text")); // NOI18N
        showLogMenuItem.addActionListener(formListener);
        viewMenu.add(showLogMenuItem);

        exploreLogFolderMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder_explore.png"))); // NOI18N
        exploreLogFolderMenuItem.setText(bundle.getString("GsplitBaseFrame.exploreLogFolderMenuItem.text")); // NOI18N
        exploreLogFolderMenuItem.addActionListener(formListener);
        viewMenu.add(exploreLogFolderMenuItem);
        viewMenu.add(jSeparator10);

        windowsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/window-manager_16x16.png"))); // NOI18N
        windowsMenu.setText("Windows");

        windowsTilesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/application_view_tile.png"))); // NOI18N
        windowsTilesMenuItem.setText(bundle.getString("GsplitBaseFrame.windowsTilesMenuItem.text")); // NOI18N
        windowsTilesMenuItem.addActionListener(formListener);
        windowsMenu.add(windowsTilesMenuItem);

        windowsCascadeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/application_cascade.png"))); // NOI18N
        windowsCascadeMenuItem.setText(bundle.getString("GsplitBaseFrame.windowsCascadeMenuItem.text")); // NOI18N
        windowsCascadeMenuItem.addActionListener(formListener);
        windowsMenu.add(windowsCascadeMenuItem);

        viewMenu.add(windowsMenu);

        baseMenuBar.add(viewMenu);

        helpMenu.setText(bundle.getString("GsplitBaseFrame.helpMenu.text")); // NOI18N

        helpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        helpMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        helpMenuItem.setText(bundle.getString("GsplitBaseFrame.helpMenuItem.text")); // NOI18N
        helpMenuItem.addActionListener(formListener);
        helpMenu.add(helpMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        aboutMenuItem.setText(bundle.getString("GsplitBaseFrame.aboutMenuItem.text")); // NOI18N
        aboutMenuItem.addActionListener(formListener);
        helpMenu.add(aboutMenuItem);

        baseMenuBar.add(helpMenu);

        setJMenuBar(baseMenuBar);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.ComponentListener, java.awt.event.MouseListener, java.awt.event.WindowListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == secureSplitButton) {
                GsplitBaseFrame.this.secureSplitButtonActionPerformed(evt);
            }
            else if (evt.getSource() == secureJoinButton) {
                GsplitBaseFrame.this.secureJoinButtonActionPerformed(evt);
            }
            else if (evt.getSource() == editSettingsButton) {
                GsplitBaseFrame.this.editSettingsButtonActionPerformed(evt);
            }
            else if (evt.getSource() == minimizeAllMenuItem) {
                GsplitBaseFrame.this.minimizeAllMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == maximizeAllMenuItem) {
                GsplitBaseFrame.this.maximizeAllMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == showAllMenuItem) {
                GsplitBaseFrame.this.showAllMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == openMdatMenuItem) {
                GsplitBaseFrame.this.openMdatMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == openLogFileMenuItem) {
                GsplitBaseFrame.this.openLogFileMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == pdfSplitMenuItem) {
                GsplitBaseFrame.this.pdfSplitMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == pdfJoinMenuItem) {
                GsplitBaseFrame.this.pdfJoinMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == xmlSplitMenuItem) {
                GsplitBaseFrame.this.xmlSplitMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == xmlJoinMenuItem) {
                GsplitBaseFrame.this.xmlJoinMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == secureSplitMenuItem) {
                GsplitBaseFrame.this.secureSplitMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == secureJoinMenuItem) {
                GsplitBaseFrame.this.secureJoinMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == flatSplitMenuItem) {
                GsplitBaseFrame.this.flatSplitMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == flatJoinMenuItem) {
                GsplitBaseFrame.this.flatJoinMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == textSplitMenuItem) {
                GsplitBaseFrame.this.textSplitMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == textJoinMenuItem) {
                GsplitBaseFrame.this.textJoinMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == minimize2trayMenuItem) {
                GsplitBaseFrame.this.minimize2trayMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == exitMenuItem) {
                GsplitBaseFrame.this.exitMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == settingsMenuItem) {
                GsplitBaseFrame.this.settingsMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == showToolbarChkbxMenuItem) {
                GsplitBaseFrame.this.showToolbarChkbxMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == showStatusbarChkbxMenuItem) {
                GsplitBaseFrame.this.showStatusbarChkbxMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == showLogMenuItem) {
                GsplitBaseFrame.this.showLogMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == exploreLogFolderMenuItem) {
                GsplitBaseFrame.this.exploreLogFolderMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == windowsTilesMenuItem) {
                GsplitBaseFrame.this.windowsTilesMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == windowsCascadeMenuItem) {
                GsplitBaseFrame.this.windowsCascadeMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == helpMenuItem) {
                GsplitBaseFrame.this.helpMenuItemActionPerformed(evt);
            }
            else if (evt.getSource() == aboutMenuItem) {
                GsplitBaseFrame.this.aboutMenuItemActionPerformed(evt);
            }
        }

        public void componentHidden(java.awt.event.ComponentEvent evt) {
        }

        public void componentMoved(java.awt.event.ComponentEvent evt) {
        }

        public void componentResized(java.awt.event.ComponentEvent evt) {
            if (evt.getSource() == baseDesktopPane) {
                GsplitBaseFrame.this.baseDesktopPaneComponentResized(evt);
            }
        }

        public void componentShown(java.awt.event.ComponentEvent evt) {
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == windowManagerLabel) {
                GsplitBaseFrame.this.windowManagerLabelMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == windowManagerLabel) {
                GsplitBaseFrame.this.windowManagerLabelMouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == windowManagerLabel) {
                GsplitBaseFrame.this.windowManagerLabelMouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == windowManagerLabel) {
                GsplitBaseFrame.this.windowManagerLabelMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == windowManagerLabel) {
                GsplitBaseFrame.this.windowManagerLabelMouseReleased(evt);
            }
        }

        public void windowActivated(java.awt.event.WindowEvent evt) {
        }

        public void windowClosed(java.awt.event.WindowEvent evt) {
        }

        public void windowClosing(java.awt.event.WindowEvent evt) {
            if (evt.getSource() == GsplitBaseFrame.this) {
                GsplitBaseFrame.this.formWindowClosing(evt);
            }
        }

        public void windowDeactivated(java.awt.event.WindowEvent evt) {
        }

        public void windowDeiconified(java.awt.event.WindowEvent evt) {
        }

        public void windowIconified(java.awt.event.WindowEvent evt) {
        }

        public void windowOpened(java.awt.event.WindowEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void flatSplitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatSplitMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.FLAT_SPLIT_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.FLAT_SPLIT_WINDOW_TITLE);
            return;
        }
        FlatSplitPanel flatSplitPanel = new FlatSplitPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(flatSplitPanel);
        baseInternalFrame.setTitle(WindowManager.FLAT_SPLIT_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-split.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_flatSplitMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        context.saveContext();
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void settingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.APP_SETTINGS_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.APP_SETTINGS_WINDOW_TITLE);
            return;
        }
        
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame();
        SettingsPanel panel = new SettingsPanel(baseInternalFrame);
        baseInternalFrame.setWorkerPanel(panel);
        baseInternalFrame.setTitle(WindowManager.APP_SETTINGS_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/settings.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_settingsMenuItemActionPerformed

    private void secureSplitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureSplitMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.SECURE_SPLIT_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.SECURE_SPLIT_WINDOW_TITLE);
            return;
        }
        SecureSplitPanel secureSplitPanel = new SecureSplitPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(secureSplitPanel);
        baseInternalFrame.setTitle(WindowManager.SECURE_SPLIT_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-split.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_secureSplitMenuItemActionPerformed

    private void secureJoinMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureJoinMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.SECURE_JOIN_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.SECURE_JOIN_WINDOW_TITLE);
            return;
        }
        SecureJoinPanel secureJoinPanel = new SecureJoinPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(secureJoinPanel);
        baseInternalFrame.setTitle(WindowManager.SECURE_JOIN_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-join.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_secureJoinMenuItemActionPerformed

    private void flatJoinMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatJoinMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.FLAT_JOIN_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.FLAT_JOIN_WINDOW_TITLE);
            return;
        }
        FlatJoinPanel panel = new FlatJoinPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(panel);
        baseInternalFrame.setTitle(WindowManager.FLAT_JOIN_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-join.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_flatJoinMenuItemActionPerformed

    private void textSplitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSplitMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.TEXT_SPLIT_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.TEXT_SPLIT_WINDOW_TITLE);
            return;
        }
        TextSplitPanel panel = new TextSplitPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(panel);
        baseInternalFrame.setTitle(WindowManager.TEXT_SPLIT_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-split.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_textSplitMenuItemActionPerformed

    private void textJoinMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJoinMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.TEXT_JOIN_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.TEXT_JOIN_WINDOW_TITLE);
            return;
        }
        TextJoinPanel panel = new TextJoinPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(panel);
        baseInternalFrame.setTitle(WindowManager.TEXT_JOIN_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-join.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_textJoinMenuItemActionPerformed

    private void openMdatMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMdatMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openMdatMenuItemActionPerformed

    private void minimize2trayMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimize2trayMenuItemActionPerformed
        ActionListener exitListener = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                context.saveContext();
                System.exit(0);
            }
        };
        WindowUtil.minimizeToTray(this, new javax.swing.ImageIcon(getClass()
                .getResource("/images/file-splitter_24x24.png")).getImage(),
                exitListener);
    }//GEN-LAST:event_minimize2trayMenuItemActionPerformed

    private void showToolbarChkbxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showToolbarChkbxMenuItemActionPerformed
        if (!showToolbarChkbxMenuItem.isSelected()) {
            baseToolBar.setVisible(false);
        } else {
            baseToolBar.setVisible(true);
        }
    }//GEN-LAST:event_showToolbarChkbxMenuItemActionPerformed

    private void showStatusbarChkbxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStatusbarChkbxMenuItemActionPerformed
        if (!showStatusbarChkbxMenuItem.isSelected()) {
            baseStatusBar.setVisible(false);
        } else {
            baseStatusBar.setVisible(true);
        }
    }//GEN-LAST:event_showStatusbarChkbxMenuItemActionPerformed

    private void showLogMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLogMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.SHOW_LOG_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.SHOW_LOG_WINDOW_TITLE);
            return;
        }
        LogViewerPanel logViewerPanel = new LogViewerPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(logViewerPanel);
        baseInternalFrame.setTitle(WindowManager.SHOW_LOG_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/file_extension_log.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_showLogMenuItemActionPerformed

    private void openLogFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openLogFileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openLogFileMenuItemActionPerformed

    private void exploreLogFolderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exploreLogFolderMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exploreLogFolderMenuItemActionPerformed

    private void helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.SHOW_HELP_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.SHOW_HELP_WINDOW_TITLE);
            return;
        }
        HelpViewerPanel panel = new HelpViewerPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(panel);
        baseInternalFrame.setTitle(WindowManager.SHOW_HELP_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/help.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_helpMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        AboutDialog aboutDialog = new AboutDialog(this, true);
        WindowUtil.bringCenterTo(aboutDialog, this);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void windowManagerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowManagerLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_windowManagerLabelMouseClicked

    private void windowManagerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowManagerLabelMouseEntered
        windowManagerLabel.setForeground(SplitterConstants.LINK_FG_COLOR);
        windowManagerLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_windowManagerLabelMouseEntered

    private void windowManagerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowManagerLabelMouseExited
        windowManagerLabel.setForeground(Color.BLACK);
        windowManagerLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_windowManagerLabelMouseExited

    private void windowManagerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowManagerLabelMousePressed
        if (MouseEvent.BUTTON1 == evt.getButton() && windowManagerLabel.isEnabled()) {
            windowManagerPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_windowManagerLabelMousePressed

    private void windowManagerLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowManagerLabelMouseReleased
        if (MouseEvent.BUTTON1 == evt.getButton() && windowManagerLabel.isEnabled()) {
            windowManagerPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_windowManagerLabelMouseReleased

    private void showAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllMenuItemActionPerformed
        WINDOW_MANAGER.showAllFrames();
    }//GEN-LAST:event_showAllMenuItemActionPerformed

    private void minimizeAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeAllMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeAllMenuItemActionPerformed

    private void maximizeAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximizeAllMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maximizeAllMenuItemActionPerformed

    private void windowsTilesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsTilesMenuItemActionPerformed
        WINDOW_MANAGER.tileWindows(baseDesktopPane);
    }//GEN-LAST:event_windowsTilesMenuItemActionPerformed

    private void pdfSplitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfSplitMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.PDF_SPLIT_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.PDF_SPLIT_WINDOW_TITLE);
            return;
        }
        PdfSplitPanel panel = new PdfSplitPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(panel);
        baseInternalFrame.setTitle(WindowManager.PDF_SPLIT_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-split.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_pdfSplitMenuItemActionPerformed

    private void pdfJoinMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfJoinMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.PDF_JOIN_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.PDF_JOIN_WINDOW_TITLE);
            return;
        }
        PdfJoinPanel panel = new PdfJoinPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(panel);
        baseInternalFrame.setTitle(WindowManager.PDF_JOIN_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-join.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_pdfJoinMenuItemActionPerformed

    private void xmlSplitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmlSplitMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.XML_SPLIT_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.XML_SPLIT_WINDOW_TITLE);
            return;
        }
        XmlSplitPanel panel = new XmlSplitPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(panel);
        baseInternalFrame.setTitle(WindowManager.XML_SPLIT_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-split.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_xmlSplitMenuItemActionPerformed

    private void xmlJoinMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmlJoinMenuItemActionPerformed
        if (WINDOW_MANAGER.containsFrame(WindowManager.XML_JOIN_WINDOW_TITLE)) {
            WINDOW_MANAGER.showFrame(WindowManager.XML_JOIN_WINDOW_TITLE);
            return;
        }
        XmlJoinPanel panel = new XmlJoinPanel();
        BaseInternalFrame baseInternalFrame = new BaseInternalFrame(panel);
        baseInternalFrame.setTitle(WindowManager.XML_JOIN_WINDOW_TITLE);
        baseInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/images/arrow-join.png")));
        WINDOW_MANAGER.addIFrame(baseInternalFrame);
    }//GEN-LAST:event_xmlJoinMenuItemActionPerformed

    private void windowsCascadeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsCascadeMenuItemActionPerformed
        WINDOW_MANAGER.cascadeWindows(baseDesktopPane);
    }//GEN-LAST:event_windowsCascadeMenuItemActionPerformed

    private void secureSplitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureSplitButtonActionPerformed
        secureSplitMenuItemActionPerformed(evt);
    }//GEN-LAST:event_secureSplitButtonActionPerformed

    private void secureJoinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureJoinButtonActionPerformed
        secureJoinMenuItemActionPerformed(evt);
    }//GEN-LAST:event_secureJoinButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        context.saveContext();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void editSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSettingsButtonActionPerformed
        settingsMenuItemActionPerformed(evt);
    }//GEN-LAST:event_editSettingsButtonActionPerformed

    private void baseDesktopPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_baseDesktopPaneComponentResized
        Dimension d = baseDesktopPane.getSize();
        int x = d.width - 264;
        int y = d.height - 244;
        desktopImageLabel.setBounds(x, y, 260, 240);
    }//GEN-LAST:event_baseDesktopPaneComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane baseDesktopPane;
    private javax.swing.JPopupMenu baseDesktopPopupMenu;
    private javax.swing.JMenuBar baseMenuBar;
    private javax.swing.JToolBar baseStatusBar;
    private javax.swing.JToolBar baseToolBar;
    private javax.swing.JLabel desktopImageLabel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton editSettingsButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exploreLogFolderMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton flatJoinButton;
    private javax.swing.JMenuItem flatJoinMenuItem;
    private javax.swing.JButton flatSplitButton;
    private javax.swing.JMenuItem flatSplitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem maximizeAllMenuItem;
    private javax.swing.JMenuItem minimize2trayMenuItem;
    private javax.swing.JMenuItem minimizeAllMenuItem;
    private javax.swing.JMenuItem openLogFileMenuItem;
    private javax.swing.JMenuItem openMdatMenuItem;
    private javax.swing.JMenuItem pdfJoinMenuItem;
    private javax.swing.JMenu pdfMenu;
    private javax.swing.JMenuItem pdfSplitMenuItem;
    private javax.swing.JButton secureJoinButton;
    private javax.swing.JMenuItem secureJoinMenuItem;
    private javax.swing.JButton secureSplitButton;
    private javax.swing.JMenuItem secureSplitMenuItem;
    private javax.swing.JMenuItem settingsMenuItem;
    private javax.swing.JMenuItem showAllMenuItem;
    private javax.swing.JMenuItem showLogMenuItem;
    private javax.swing.JCheckBoxMenuItem showStatusbarChkbxMenuItem;
    private javax.swing.JCheckBoxMenuItem showToolbarChkbxMenuItem;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JMenuItem textJoinMenuItem;
    private javax.swing.JMenu textMenu;
    private javax.swing.JMenuItem textSplitMenuItem;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JLabel windowManagerLabel;
    private javax.swing.JPopupMenu windowManagerPopupMenu;
    private javax.swing.JMenuItem windowsCascadeMenuItem;
    private javax.swing.JMenu windowsMenu;
    private javax.swing.JMenuItem windowsTilesMenuItem;
    private javax.swing.JMenuItem xmlJoinMenuItem;
    private javax.swing.JMenu xmlMenu;
    private javax.swing.JMenuItem xmlSplitMenuItem;
    // End of variables declaration//GEN-END:variables
}
