/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.sf.tools.gsplit.ui;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author SG1736
 */
public class HelpViewerPanel extends javax.swing.JPanel {


    /**
     * Creates new form HelpViewerPanel
     */
    public HelpViewerPanel() {
        initComponents();
        htmlEditorPane.setContentType("text/html");
        
        try {
            File file = new File("./help/gsplit-help-0.0.2.html");
            if(file.exists()){
                htmlEditorPane.setPage("file:///"+file.getAbsoluteFile());
            }
            else {
                htmlEditorPane.setText("<html>Could not find Help file </html>");
            }
        } catch (Exception e) {
            htmlEditorPane.setText("<html>" + e.getMessage()+" </html>");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        htmlEditorPane = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        htmlEditorPane.setEditable(false);
        jScrollPane2.setViewportView(htmlEditorPane);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane htmlEditorPane;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
