SELECT     
BATCH_JOB_EXECUTION.EXIT_CODE, BATCH_JOB_EXECUTION.EXIT_MESSAGE, BATCH_STEP_EXECUTION.STEP_NAME, 
BATCH_STEP_EXECUTION.COMMIT_COUNT, BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT, 
BATCH_JOB_INSTANCE.JOB_NAME, BATCH_JOB_INSTANCE.VERSION, BATCH_JOB_INSTANCE.JOB_INSTANCE_ID, 
BATCH_STEP_EXECUTION.READ_COUNT, BATCH_STEP_EXECUTION.WRITE_COUNT, BATCH_STEP_EXECUTION.READ_SKIP_COUNT, 
BATCH_STEP_EXECUTION.WRITE_SKIP_COUNT, BATCH_STEP_EXECUTION.STATUS, 
BATCH_STEP_EXECUTION.START_TIME AS STEP_START_TIME, BATCH_STEP_EXECUTION.END_TIME AS STEP_END_TIME, 
BATCH_JOB_EXECUTION.START_TIME AS JOB_START_TIME, BATCH_JOB_EXECUTION.END_TIME AS JOB_END_TIME
FROM         
BATCH_JOB_EXECUTION INNER JOIN
BATCH_JOB_EXECUTION_CONTEXT ON 
BATCH_JOB_EXECUTION.JOB_EXECUTION_ID = BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID INNER JOIN
BATCH_JOB_INSTANCE ON BATCH_JOB_EXECUTION.JOB_INSTANCE_ID = BATCH_JOB_INSTANCE.JOB_INSTANCE_ID INNER JOIN
BATCH_JOB_PARAMS ON BATCH_JOB_INSTANCE.JOB_INSTANCE_ID = BATCH_JOB_PARAMS.JOB_INSTANCE_ID INNER JOIN
BATCH_STEP_EXECUTION ON 
BATCH_JOB_EXECUTION.JOB_EXECUTION_ID = BATCH_STEP_EXECUTION.JOB_EXECUTION_ID INNER JOIN
BATCH_STEP_EXECUTION_CONTEXT ON 
BATCH_STEP_EXECUTION.STEP_EXECUTION_ID = BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID


SELECT 
	BATCH_JOB_INSTANCE.JOB_NAME,
	BATCH_JOB_EXECUTION.EXIT_CODE,
	BATCH_JOB_EXECUTION.EXIT_MESSAGE,
	BATCH_JOB_INSTANCE.JOB_INSTANCE_ID,
	BATCH_JOB_EXECUTION.START_TIME AS JOB_START_TIME,
	BATCH_JOB_EXECUTION.END_TIME AS JOB_END_TIME

FROM 
	BATCH_JOB_EXECUTION INNER JOIN 
	BATCH_JOB_INSTANCE ON BATCH_JOB_EXECUTION.JOB_INSTANCE_ID = BATCH_JOB_INSTANCE.JOB_INSTANCE_ID
	
SELECT 
	BATCH_JOB_INSTANCE.JOB_INSTANCE_ID,
	BATCH_JOB_INSTANCE.JOB_NAME,
	BATCH_JOB_EXECUTION.EXIT_CODE,
	BATCH_JOB_EXECUTION.EXIT_MESSAGE,
	BATCH_JOB_EXECUTION.START_TIME AS JOB_START_TIME,
	BATCH_JOB_EXECUTION.END_TIME AS JOB_END_TIME

FROM 
	BATCH_JOB_EXECUTION INNER JOIN 
	BATCH_JOB_INSTANCE ON BATCH_JOB_EXECUTION.JOB_INSTANCE_ID = BATCH_JOB_INSTANCE.JOB_INSTANCE_ID