/** ---------------------------------------------------------------------------*
 * Copyright Sabuj Das | sabuj.das@gmail.com all rights reserved.
 * <br/>
 * This document cannot be copied, modified or re-distributed without prior 
 * permission from the author.
 *  ---------------------------------------------------------------------------* 
 * Type     : com.gs.tools.colorhound.ui.ColorHoundBaseFrame
 * Date     : May 23, 2013
 */

package com.gs.tools.colorhound.ui;

import com.gs.tools.colorhound.event.ApplicationEventManager;
import com.gs.tools.colorhound.event.ColorGrabEvent;
import com.gs.tools.colorhound.event.ColorGrabListener;
import com.gs.tools.colorhound.event.ColorPanelSelectedEvent;
import com.gs.tools.colorhound.event.ColorPanelSelectedEventListener;
import com.gs.tools.colorhound.event.ExternalEventListener;
import java.awt.AWTEvent;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Sabuj Das | sabuj.das@gmail.com
 */
public class ColorHoundBaseFrame extends javax.swing.JFrame 
    implements ColorGrabListener, ColorPanelSelectedEventListener{

    private ApplicationEventManager eventManager 
            = ApplicationEventManager.getInstance();
    
    /** Creates new form ColorHoundBaseFrame */
    public ColorHoundBaseFrame() {
        initComponents();
        
        ExternalEventListener externalEventListener
                = new ExternalEventListener();
        Toolkit.getDefaultToolkit().addAWTEventListener(
            externalEventListener, 
            AWTEvent.KEY_EVENT_MASK | AWTEvent.MOUSE_MOTION_EVENT_MASK);
        
        ApplicationEventManager.getInstance().registerListener(
                ColorPanelSelectedEvent.class, this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseContentPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        paletteToolBar = new javax.swing.JToolBar();
        jLabel5 = new javax.swing.JLabel();
        paletteListComboBox = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        addColorButton = new javax.swing.JButton();
        editColorButton = new javax.swing.JButton();
        deleteColorButton = new javax.swing.JButton();
        paletteContentPanel = new javax.swing.JPanel();
        colorDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        redRgbTextField = new javax.swing.JTextField();
        greenRgbTextField = new javax.swing.JTextField();
        blueRgbTextField = new javax.swing.JTextField();
        cssRgbTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        hexColorTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        enlargedPanel = new javax.swing.JPanel();
        colorSourceTabbedPane = new javax.swing.JTabbedPane();
        imageViewerPanel = new javax.swing.JPanel();
        imageControlToolBar = new javax.swing.JToolBar();
        openImageButton = new javax.swing.JButton();
        imageContainerPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        baseMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        hideMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(730, 480));
        setPreferredSize(new java.awt.Dimension(730, 480));
        addKeyListener(formListener);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/Message"); // NOI18N
        leftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("lbl.palette.panel.header"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(153, 153, 255))); // NOI18N

        paletteToolBar.setFloatable(false);
        paletteToolBar.setRollover(true);

        jLabel5.setText(bundle.getString("lbl.palette.list")); // NOI18N
        paletteToolBar.add(jLabel5);

        paletteListComboBox.setMaximumSize(new java.awt.Dimension(280, 32767));
        paletteListComboBox.setMinimumSize(new java.awt.Dimension(180, 20));
        paletteListComboBox.setPreferredSize(new java.awt.Dimension(280, 20));
        paletteListComboBox.addItemListener(formListener);
        paletteListComboBox.addPropertyChangeListener(formListener);
        paletteToolBar.add(paletteListComboBox);
        paletteToolBar.add(jSeparator2);

        addColorButton.setText(bundle.getString("lbl.add.color.button")); // NOI18N
        addColorButton.setEnabled(false);
        addColorButton.setFocusable(false);
        addColorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addColorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addColorButton.addActionListener(formListener);
        paletteToolBar.add(addColorButton);

        editColorButton.setText(bundle.getString("lbl.edit.color.button")); // NOI18N
        editColorButton.setEnabled(false);
        editColorButton.setFocusable(false);
        editColorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editColorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editColorButton.addActionListener(formListener);
        paletteToolBar.add(editColorButton);

        deleteColorButton.setText(bundle.getString("lbl.delete.color.button")); // NOI18N
        deleteColorButton.setEnabled(false);
        deleteColorButton.setFocusable(false);
        deleteColorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteColorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteColorButton.addActionListener(formListener);
        paletteToolBar.add(deleteColorButton);

        paletteContentPanel.setBackground(new java.awt.Color(0, 0, 0));
        paletteContentPanel.setComponentOrientation(
            ComponentOrientation.RIGHT_TO_LEFT);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paletteToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(paletteContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(paletteToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paletteContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Red");

        jLabel2.setText("Green");

        jLabel3.setText("Blue");

        jLabel4.setText("HEX");

        redRgbTextField.setForeground(java.awt.Color.red);
        redRgbTextField.setMinimumSize(new java.awt.Dimension(50, 20));
        redRgbTextField.setPreferredSize(new java.awt.Dimension(50, 20));

        greenRgbTextField.setForeground(java.awt.Color.green);
        greenRgbTextField.setMinimumSize(new java.awt.Dimension(50, 20));
        greenRgbTextField.setPreferredSize(new java.awt.Dimension(50, 20));

        blueRgbTextField.setForeground(java.awt.Color.blue);
        blueRgbTextField.setMinimumSize(new java.awt.Dimension(50, 20));
        blueRgbTextField.setPreferredSize(new java.awt.Dimension(50, 20));

        cssRgbTextField.addActionListener(formListener);

        jButton1.setText(bundle.getString("lbl.copy.button")); // NOI18N
        jButton1.setEnabled(false);
        jButton1.addActionListener(formListener);

        jButton2.setText(bundle.getString("lbl.copy.button")); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(formListener);

        jButton3.setText(bundle.getString("lbl.copy.button")); // NOI18N
        jButton3.setEnabled(false);
        jButton3.addActionListener(formListener);

        jLabel6.setText(bundle.getString("lbl.rgb")); // NOI18N

        jLabel7.setText("CSS");

        javax.swing.GroupLayout colorDetailsPanelLayout = new javax.swing.GroupLayout(colorDetailsPanel);
        colorDetailsPanel.setLayout(colorDetailsPanelLayout);
        colorDetailsPanelLayout.setHorizontalGroup(
            colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                        .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hexColorTextField))
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cssRgbTextField)))
                        .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorDetailsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))))
                    .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1))
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redRgbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2))
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(greenRgbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3))
                            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueRgbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        colorDetailsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel6, jLabel7});

        colorDetailsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        colorDetailsPanelLayout.setVerticalGroup(
            colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(redRgbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenRgbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueRgbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(4, 4, 4)
                .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hexColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cssRgbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        colorDetailsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {blueRgbTextField, cssRgbTextField, greenRgbTextField, hexColorTextField, jButton1, jButton2, jButton3, jLabel4, jLabel6, jLabel7, redRgbTextField});

        colorDetailsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("lbl.enlarged.header"))); // NOI18N

        enlargedPanel.setBackground(new java.awt.Color(255, 255, 255));
        enlargedPanel.setMaximumSize(new java.awt.Dimension(100, 100));
        enlargedPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        enlargedPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout enlargedPanelLayout = new javax.swing.GroupLayout(enlargedPanel);
        enlargedPanel.setLayout(enlargedPanelLayout);
        enlargedPanelLayout.setHorizontalGroup(
            enlargedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        enlargedPanelLayout.setVerticalGroup(
            enlargedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enlargedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enlargedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        imageViewerPanel.setLayout(new java.awt.BorderLayout());

        imageControlToolBar.setFloatable(false);
        imageControlToolBar.setRollover(true);

        openImageButton.setText(bundle.getString("lbl.open.image.button")); // NOI18N
        openImageButton.setFocusable(false);
        openImageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openImageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openImageButton.addActionListener(formListener);
        imageControlToolBar.add(openImageButton);

        imageViewerPanel.add(imageControlToolBar, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout imageContainerPanelLayout = new javax.swing.GroupLayout(imageContainerPanel);
        imageContainerPanel.setLayout(imageContainerPanelLayout);
        imageContainerPanelLayout.setHorizontalGroup(
            imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        imageContainerPanelLayout.setVerticalGroup(
            imageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        imageViewerPanel.add(imageContainerPanel, java.awt.BorderLayout.CENTER);

        colorSourceTabbedPane.addTab(bundle.getString("lbl.image.tab.title"), imageViewerPanel); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        colorSourceTabbedPane.addTab("tab2", jPanel3);

        javax.swing.GroupLayout baseContentPanelLayout = new javax.swing.GroupLayout(baseContentPanel);
        baseContentPanel.setLayout(baseContentPanelLayout);
        baseContentPanelLayout.setHorizontalGroup(
            baseContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseContentPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(baseContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorSourceTabbedPane)
                    .addGroup(baseContentPanelLayout.createSequentialGroup()
                        .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addGroup(baseContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(colorDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(1, 1, 1))
        );
        baseContentPanelLayout.setVerticalGroup(
            baseContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseContentPanelLayout.createSequentialGroup()
                .addGroup(baseContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(leftPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(baseContentPanelLayout.createSequentialGroup()
                        .addComponent(colorDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(colorSourceTabbedPane)
                .addGap(2, 2, 2))
        );

        getContentPane().add(baseContentPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText(bundle.getString("lbl.file.menu")); // NOI18N

        newMenuItem.setText(bundle.getString("lbl.new.menu.item")); // NOI18N
        newMenuItem.addActionListener(formListener);
        fileMenu.add(newMenuItem);
        fileMenu.add(jSeparator1);

        hideMenuItem.setText(bundle.getString("lbl.hide.menu.item")); // NOI18N
        fileMenu.add(hideMenuItem);

        exitMenuItem.setText(bundle.getString("lbl.exit.menu.item")); // NOI18N
        fileMenu.add(exitMenuItem);

        baseMenuBar.add(fileMenu);

        jMenu2.setText("Edit");
        baseMenuBar.add(jMenu2);

        setJMenuBar(baseMenuBar);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.ItemListener, java.awt.event.KeyListener, java.beans.PropertyChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == addColorButton) {
                ColorHoundBaseFrame.this.addColorButtonActionPerformed(evt);
            }
            else if (evt.getSource() == editColorButton) {
                ColorHoundBaseFrame.this.editColorButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteColorButton) {
                ColorHoundBaseFrame.this.deleteColorButtonActionPerformed(evt);
            }
            else if (evt.getSource() == cssRgbTextField) {
                ColorHoundBaseFrame.this.cssRgbTextFieldActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                ColorHoundBaseFrame.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                ColorHoundBaseFrame.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton3) {
                ColorHoundBaseFrame.this.jButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == openImageButton) {
                ColorHoundBaseFrame.this.openImageButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newMenuItem) {
                ColorHoundBaseFrame.this.newMenuItemActionPerformed(evt);
            }
        }

        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            if (evt.getSource() == paletteListComboBox) {
                ColorHoundBaseFrame.this.paletteListComboBoxItemStateChanged(evt);
            }
        }

        public void keyPressed(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == ColorHoundBaseFrame.this) {
                ColorHoundBaseFrame.this.formKeyPressed(evt);
            }
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == ColorHoundBaseFrame.this) {
                ColorHoundBaseFrame.this.formKeyReleased(evt);
            }
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
        }

        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            if (evt.getSource() == paletteListComboBox) {
                ColorHoundBaseFrame.this.paletteListComboBoxPropertyChange(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        
    }//GEN-LAST:event_formKeyReleased

    private void deleteColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteColorButtonActionPerformed
        if(null != ColorPaletteManager.getInstance().getSelectPanel()){
            paletteContentPanel.remove(ColorPaletteManager.getInstance().getSelectPanel());
            paletteContentPanel.updateUI();
            ColorPaletteManager.getInstance().removeSelectedPanel(getPaletteName());
            ColorPanelSelectedEvent event = new ColorPanelSelectedEvent
                (true, false, this);
            ApplicationEventManager.getInstance().fireEvent(event);
        }
    }//GEN-LAST:event_deleteColorButtonActionPerformed

    private void addColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addColorButtonActionPerformed
        String palette = getPaletteName();
        if(!"".equals(palette)){
            ColorPanel colorPanel = new ColorPanel(paletteContentPanel, getPaletteName());
            ColorPaletteManager.getInstance().addPanel(getPaletteName(), colorPanel);
            paletteContentPanel.add(colorPanel, FlowLayout.LEFT);
            paletteContentPanel.updateUI();
        }
        else {
            JOptionPane.showMessageDialog(this, "Plase add a Palette...");
        }
        
    }//GEN-LAST:event_addColorButtonActionPerformed

    private void editColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editColorButtonActionPerformed
    	ColorPaletteManager.getInstance().makeSelectedColorPanelEditable(getPaletteName());
    }//GEN-LAST:event_editColorButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void openImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openImageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openImageButtonActionPerformed

    private void cssRgbTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cssRgbTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cssRgbTextFieldActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        String name = JOptionPane.showInputDialog(this, "Enter a Palette Name: ");
        ColorPaletteManager.getInstance().addPalette(name);
        paletteListComboBox.addItem(name);
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void paletteListComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_paletteListComboBoxPropertyChange
        addColorButton.setEnabled(true);
    }//GEN-LAST:event_paletteListComboBoxPropertyChange

    private void paletteListComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paletteListComboBoxItemStateChanged
        
    }//GEN-LAST:event_paletteListComboBoxItemStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addColorButton;
    private javax.swing.JPanel baseContentPanel;
    private javax.swing.JMenuBar baseMenuBar;
    private javax.swing.JTextField blueRgbTextField;
    private javax.swing.JPanel colorDetailsPanel;
    private javax.swing.JTabbedPane colorSourceTabbedPane;
    private javax.swing.JTextField cssRgbTextField;
    private javax.swing.JButton deleteColorButton;
    private javax.swing.JButton editColorButton;
    private javax.swing.JPanel enlargedPanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField greenRgbTextField;
    private javax.swing.JTextField hexColorTextField;
    private javax.swing.JMenuItem hideMenuItem;
    private javax.swing.JPanel imageContainerPanel;
    private javax.swing.JToolBar imageControlToolBar;
    private javax.swing.JPanel imageViewerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JButton openImageButton;
    private javax.swing.JPanel paletteContentPanel;
    private javax.swing.JComboBox paletteListComboBox;
    private javax.swing.JToolBar paletteToolBar;
    private javax.swing.JTextField redRgbTextField;
    // End of variables declaration//GEN-END:variables

    public void colorGrabbed(ColorGrabEvent event) {
        System.out.println(event.getNewValue());
    }

    
    public String getPaletteName(){
        return (null != paletteListComboBox.getSelectedItem())
                ? paletteListComboBox.getSelectedItem().toString() : "";
    }

    public void colorPanelSelected(ColorPanelSelectedEvent event) {
        if(event.getNewValue()){
            editColorButton.setEnabled(true);
            deleteColorButton.setEnabled(true);
            if(event.getSelectedColor() != null){
                redRgbTextField.setText(""+event.getSelectedColor().getRed());
                greenRgbTextField.setText(""+event.getSelectedColor().getGreen());
                blueRgbTextField.setText(""+event.getSelectedColor().getBlue());
            }
        } else {
            editColorButton.setEnabled(false);
            deleteColorButton.setEnabled(false);
        }
    }
    
    
}
